#!/bin/bash
# Get the status of Boundary conditions for ReFRESCO, and export it to HTML tables

result=$(grep '^\ *BCType.*NEUMANN\|^\ *BCType.*DIRICHLET' $REFRESCO_CODE_DIR/src/*F90 | \
    sed 's/^.*\///;s/!.*$//;s/BCType//;s/[(|)]//g;s/=/:/;s/\ //g' |\
    awk -F':' '{print $2 ":" $1 ":" $3}')

BC_list=$(awk -F':' '{print $1}' <<<$result | sort | uniq)
file_list=$(awk -F':' '{print $2}' <<<$result | sort | uniq)


echo '<style>
tr, td {
  padding: 7px;
  padding-right: 15px;
}
th {
  text-align: center;
}
table {
  border: 1px solid black;
  width: 100%;
}
</style>'

echo '<table>'
echo '<th>BC</th>'

for BC in $BC_list
do
    echo '<th>'$BC'</th>'
done

for file in $file_list
do
    echo '<tr>'
    echo '<th>'$file'</th>'

    for BC in $BC_list
    do
        values=$(grep -m 1 "^${BC}:$file" <<<"$result" | awk -F':' '{print $3}')
        echo '<td>' $values '</td>'
    done

    echo '</tr>'
done
echo '</table>'
