#!/bin/bash
# Get the status of Boundary conditions for ReFRESCO, and export it to HTML tables

result=$(grep '^\ *BCType.*NEUMANN\|^\ *BCType.*DIRICHLET' $REFRESCO_CODE_DIR/src/*F90 | \
    sed 's/^.*\///;s/!.*$//;s/BCType//;s/[(|)]//g;s/=/:/;s/\ //g' |\
    awk -F':' '{print $2 ":" $1 ":" $3}')

BC_list=$(awk -F':' '{print $1}' <<<$result | sort | uniq)
file_list=$(awk -F':' '{print $2}' <<<$result | sort | uniq)


echo '<style>
th {
  text-align: left;
}
th, td, tr {
  padding-left: 10px;
  padding-right: 10px;
}
.NEUMANN {
 color: #B0000A;
}
.DIRICHLET {
 color: #0049B0;
}
</style>'

echo '<table>'
echo '<th>BC</th>'

for file in $file_list
do
    echo '<th>'$file'</th>' | sed 's/\.F90//'
done

for BC in $BC_list
do
    echo '<tr>'
    echo '<th>'$BC'</th>'

    for file in $file_list
    do
        values=$(grep -m 1 "^${BC}:$file" <<<"$result" | awk -F':' '{print $3}')
        nb=$(grep -c "^${BC}:$file" <<<"$result")
        if [[ "$nb" -gt 1 ]]
        then
            nb='*'
        else
            nb=''
        fi
        echo '<td class="'$values'">'$values$nb'</td>'
    done

    echo '</tr>'
done
echo '</table>'
